import type { Metadata } from "next";
import "@/styles/globals.css";
import { ProductContextProvider } from "@/context/ProductContext";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "ECOM-MERN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProductContextProvider
          child={
            <>
              {children}
              <Footer />
            </>
          }
        ></ProductContextProvider>
      </body>
    </html>
  );
}
